In [1]:
import numpy as np

In [9]:
a = np.arange(8).reshape(4,-1) ##
# use linspace for float step size range func
b = np.array([[1,2],[3,4]]) ##
print(b)
print(a)
print(type(a)) ##
print(np.shape(a)) ##

[[1 2]
 [3 4]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
<class 'numpy.ndarray'>
(4, 2)


In [13]:
A = np.ones((2,3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
print(np.random.rand(2,3))

[[0.08720457 0.67934248 0.34575841]
 [0.99840123 0.66510825 0.54125885]]
