In [13]:
import torch
import numpy as np

## Initialization

In [9]:
x = torch.empty(5,3)                        # no init (garbage values)
print(x)
y = torch.rand(5,3)                         # random init
print(y)
x = torch.zeros(5, 3, dtype=torch.long)     # zero init
x = torch.ones(5, 3, dtype=torch.long)      # one init
print(x)
x = torch.tensor([5.5, 3])                  # direct/manual init 
print(x)
x = x.new_ones(5, 3, dtype=torch.double)    # reinit with ones
print(x)
x = torch.randn_like(x, dtype=torch.float)  # copy init
print(x)

tensor([[1.8561, 3.6522, 2.2875],
        [1.0793, 1.0052, 0.3869],
        [1.8718, 0.8598, 1.5903],
        [0.3330, 0.2687, 0.5109],
        [0.6580, 0.1315, 1.1216]])
tensor([[0.9866, 0.2769, 0.3505],
        [0.9004, 0.8409, 0.3463],
        [0.3803, 0.0256, 0.0243],
        [0.1602, 0.9902, 0.6624],
        [0.2770, 0.2258, 0.9288]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.9707,  0.1736,  0.0127],
        [-0.3257, -0.1465,  0.7252],
        [ 0.3253, -0.5616, -0.7376],
        [ 1.0626, -0.0039, -0.5750],
        [ 0.7591,  0.8005, -1.5758]])


### NOTE

- **new_empty** is used with a *tensor var* whereas **empty** is used with/an attribute of "*torch*". 
- **new_*** methods take in sizes and are used to reinitialize a var with new values.
- **_** is an *inplace* operation. Modifies the variable that calls it.(eg- x.copy_(y), x.add_(y), x.t_()


## Indexing
- Standard Indexing (just as in **NumPy**)
- Other attributes same as that of NumPy

## Utility Functions

In [8]:
print(x.size())

torch.Size([5, 3])


| Function           | Description               | Example             |
| ------------------ | ------------------------- | ------------------- |
| size               | size of Tensor            | x.size()            |
| t                  | Transpose                 | x.t()               |
| add                | Add                       | x.add(y)            |
| copy               | Copy                      | x.copy(y)           |
| view               | Resize                    | x.view()            |
| numpy              | Tensor to Numpy converter | x.numpy()           |
| torch.from_numpy() | Numpy to Tensor converter | torch.from_numpy(x) |
| 

### NOTE
- **torch.Size** is a tuple.


In [13]:
# 2 ways of addition
print(x + y)            # 1
print(torch.add(x,y))   # 2

# resize operation 
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  
print(x.size(), y.size(), z.size())


tensor([[ 1.9573,  0.4505,  0.3632],
        [ 0.5747,  0.6943,  1.0715],
        [ 0.7056, -0.5359, -0.7132],
        [ 1.2227,  0.9863,  0.0874],
        [ 1.0361,  1.0263, -0.6470]])
tensor([[ 1.9573,  0.4505,  0.3632],
        [ 0.5747,  0.6943,  1.0715],
        [ 0.7056, -0.5359, -0.7132],
        [ 1.2227,  0.9863,  0.0874],
        [ 1.0361,  1.0263, -0.6470]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


## General attributes of functions

- **out** = var_name -> to output value of operation to var_name variable

## CUDA Tensors
- **.to()** to choose a device
- argument can be either a string or a device object

In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [18]:
import numpy as np
from scipy import linalg
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])

In [19]:
print(linalg.det(A))
print(linalg.det(B))
print(linalg.det(A*B))

-2.0
-2.0
-20.0


In [21]:
print(linalg.det(np.dot(A,B)))


[[ 7 10]
 [15 22]]


In [3]:
import torch

In [6]:
tensor = torch.Tensor([[1,2],[3,4]]) # Tensor/tensor - both upper and lower case work
print(tensor)
print(tensor.type)
print(tensor.shape)

tensor([[1., 2.],
        [3., 4.]])
<built-in method type of Tensor object at 0x00000130AD4C29A8>
torch.Size([2, 2])


In [11]:
print(torch.ones(2,3))
print(torch.ones((2,3)))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [12]:
print(torch.rand(2,3))

tensor([[0.9521, 0.8108, 0.0685],
        [0.8779, 0.7351, 0.6844]])


In [15]:
a = np.random.rand(2,3)
b = torch.from_numpy(a)
print(torch.from_numpy(a))
print(b.numpy())

tensor([[0.9582, 0.1458, 0.7755],
        [0.5244, 0.2964, 0.9530]], dtype=torch.float64)
[[0.95815169 0.14581256 0.7755147 ]
 [0.52436974 0.29640201 0.9529958 ]]


In [26]:
a = torch.ones(3,3)
# view -> resahape

print(a.view(9)) 
print(a.view(9).shape)
# print(tensor.view(9).shape)
print(a)

print(torch.add(a,a))
print(torch.sub(a,a))
print(a.sub(a))
print(torch.mul(a,a))
print(torch.div(a,a))
print(a.mean())
print(a.std())

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])
torch.Size([9])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor(1.)
tensor(0.)


In [29]:
# variable accumulates gradients 
# tensor does not
# variables for backward propagation

from torch.autograd import Variable # variable also works
var = Variable(torch.ones(3), requires_grad=True)
var

tensor([1., 1., 1.], requires_grad=True)

In [41]:
ar = torch.Tensor([2,4])
x = Variable(ar, requires_grad=True)
# y = Variable(x**2)
x.requires_grad = True
y = x**2

print(y)

err = 1/2*sum(y)
print(err)

err.backward()

print(x.grad)

tensor([ 4., 16.], requires_grad=True)
tensor(10., grad_fn=<MulBackward0>)
None
tensor([0.5000, 0.5000])
